const countriesName = {
    "USA": "أمريكا",
    "India": "الهند",
    "Brazil": "البرازيل",
    "France": "فرنسا",
    "Turkey": "تركيا",
    "Russia": "روسيا",
    "UK": "إنجلترا",
    "Italy": "إيطاليا",
    "Argentina": "الأرجنتين",
    "Colombia": "كولومبيا",
    "Spain": "إسبانيا",
    "Germany": "ألمانيا",
    "Iran": "إيران",
    "Poland": "بولندا",
    "Mexico": "المكسيك",
    "Ukraine": "أوكرانيا",
    "Peru": "بيرو",
    "Indonesia": "إندونيسيا",
    "South Africa": "جنوب أفريقيا",
    "Netherlands": "هولندا",
    "Czechia": "التشيك",
    "Chile": "شيلي",
    "Canada": "كندا",
    "Philippines": "فيلبيني",
    "Iraq": "العراق",
    "Sweden": "السويد",
    "Romania": "رومانيا",
    "Belgium": "بلجيكا",
    "Pakistan": "باكستان",
    "Portugal": "البرتغال",
    "Bangladesh": "بنغلاديش",
    "Israel": "إسرائيل",
    "Hungary": "هنغاريا",
    "Japan": "اليابان",
    "Jordan": "الأردن",
    "Serbia": "صربيا",
    "Switzerland": "سويسرا",
    "Malaysia": "ماليزيا",
    "Austria": "النمسا",
    "Nepal": "نيبال",
    "UAE": "الإمارات العربية المتحدة",
    "Lebanon": "لبنان",
    "Morocco": "المغرب",
    "Saudi Arabia": "المملكة العربية السعودية",
    "Ecuador": "إكوادور",
    "Bulgaria": "بلغاريا",
    "Greece": "اليونان",
    "Bolivia": "بوليفيا",
    "Belarus": "بيلاروس",
    "Kazakhstan": "كازاخستان",
    "Paraguay": "باراغواي",
    "Slovakia": "سلوفاكيا",
    "Panama": "بنما",
    "Tunisia": "تونس",
    "Croatia": "كرواتيا",
    "Georgia": "جورجيا",
    "Costa Rica": "كوستاريكا",
    "Uruguay": "أوروغواي",
    "Azerbaijan": "أذربيجان",
    "Kuwait": "الكويت",
    "Dominican Republic": "جمهورية الدومينيكان",
    "Palestine": "فلسطين",
    "Denmark": "الدنمارك",
    "Lithuania": "ليتوانيا",
    "Guatemala": "غواتيمالا",
    "Egypt": "مصر",
    "Ethiopia": "أثيوبيا",
    "Ireland": "أيرلندا",
    "Bahrain": "البحرين",
    "Slovenia": "سلوفينيا",
    "Venezuela": "فنزويلا",
    "Moldova": "مولدوفا",
    "Honduras": "هندوراس",
    "Oman": "سلطنة عمان",
    "Sri Lanka": "سيريلانكا",
    "Armenia": "أرمينيا",
    "Qatar": "دولة قطر",
    "Thailand": "تايلاند",
    "Bosnia": "البوسنة",
    "Libyan Arab Jamahiriya": "ليبيا",
    "Kenya": "كينيا",
    "Nigeria": "نيجيريا",
    "Cuba": "كوبا",
    "Macedonia": "مقدونيا",
    "S. Korea": "كوريا الجنوبية",
    "Myanmar": "ميانمار",
    "Latvia": "لاتفيا",
    "Algeria": "الجزائر",
    "Albania": "ألبانيا",
    "Estonia": "إستونيا",
    "Norway": "النرويج",
    "Zambia": "زامبيا",
    "Kyrgyzstan": "قيرغيزستان",
    "Uzbekistan": "أوزبكستان",
    "Montenegro": "الجبل الأسود",
    "Afghanistan": "أفغانستان",
    "Ghana": "غانا",
    "Finland": "فنلندا",
    "China": "الصين",
    "Mongolia": "منغوليا",
    "Cameroon": "الكاميرون",
    "El Salvador": "السلفادور",
    "Cyprus": "قبرص",
    "Mozambique": "موزامبيق",
    "Maldives": "ملديف",
    "Luxembourg": "لوكسمبورغ",
    "Namibia": "ناميبيا",
    "Uganda": "أوغندا",
    "Botswana": "بوتسوانا",
    "Singapore": "سنغافورة",
    "Jamaica": "جامايكا",
    "Côte d'Ivoire": "كوت ديفوار",
    "Senegal": "السنغال",
    "Madagascar": "مدغشقر",
    "Cambodia": "كمبوديا",
    "Zimbabwe": "زمبابوي",
    "Angola": "أنغولا",
    "DRC": "الكنغو",
    "Sudan": "السودان",
    "Malawi": "ملاوي",
    "Cabo Verde": "كابو فيردي",
    "Malta": "مالطا",
    "Australia": "أستراليا",
    "Trinidad and Tobago": "ترينداد وتوباغو",
    "Rwanda": "رواندا",
    "Réunion": "جمع شمل",
    "French Guiana": "غيانا الفرنسية",
    "Syrian Arab Republic": "سوريا",
    "Gabon": "الجابون",
    "Guinea": "غينيا",
    "Mauritania": "موريتانيا",
    "Mayotte": "مايوت",
    "Suriname": "سورينام",
    "French Polynesia": "بولينيزيا الفرنسية",
    "Swaziland": "سوازيلند",
    "Guyana": "غيانا",
    "Haiti": "هايتي",
    "Papua New Guinea": "غينيا",
    "Guadeloupe": "جوادلوب",
    "Somalia": "الصومال",
    "Mali": "مالي",
    "Seychelles": "سيشيل",
    "Andorra": "أندورا",
    "Taiwan": "تايوان",
    "Togo": "توجو",
    "Burkina Faso": "بوركينا فاسو",
    "Tajikistan": "طاجيكستان",
    "Belize": "بليز",
    "Vietnam": "فيتنام",
    "Curaçao": "كوراساو",
    "Congo": "الكونغو",
    "Bahamas": "جزر البهاما",
    "Martinique": "مارتينيك",
    "Hong Kong": "هونغ كونغ",
    "Djibouti": "جيبوتي",
    "Aruba": "أروبا",
    "Lesotho": "ليسوتو",
    "South Sudan": "جنوب السودان",
    "Equatorial Guinea": "غينيا الإستوائية",
    "Timor-Leste": "تيمور - ليشتي",
    "Benin": "بنن",
    "Nicaragua": "نيكاراغوا",
    "Central African Republic": "جمهورية افريقيا الوسطى",
    "Yemen": "اليمن",
    "Iceland": "أيسلندا",
    "Gambia": "غامبيا",
    "Niger": "النيجر",
    "Eritrea": "إريتريا",
    "Saint Lucia": "القديسة لوسيا",
    "Burundi": "بوروندي",
    "San Marino": "سان مارينو",
    "Chad": "تشاد",
    "Sierra Leone": "سيرا ليون",
    "Gibraltar": "جبل طارق",
    "Channel Islands": "جزر القناة",
    "Barbados": "بربادوس",
    "Comoros": "جزر القمر",
    "Guinea-Bissau": "غينيا - بيساو",
    "Liechtenstein": "ليختنشتاين",
    "Liberia": "ليبيريا",
    "New Zealand": "نيوزيلاندا",
    "Sint Maarten": "سينت مارتن",
    "Monaco": "موناكو",
    "Bermuda": "برمودا",
    "Turks and Caicos Islands": "جزر تركس وكايكوس",
    "Sao Tome and Principe": "سان تومي وبرينسيبي",
    "Saint Vincent and the Grenadines": "سانت فنسنت وجزر غرينادين",
    "Saint Martin": "القديس مارتن",
    "Lao People's Democratic Republic": "جمهورية لاو الديمقراطية الشعبية",
    "Bhutan": "بوتان",
    "Mauritius": "موريشيوس",
    "Caribbean Netherlands": "منطقة البحر الكاريبي الهولندية",
    "Isle of Man": "جزيرة آيل أوف مان",
    "Fiji": "فيجي",
    "Antigua and Barbuda": "أنتيغوا وبربودا",
    "St. Barth": "سانت بارث",
    "Faroe Islands": "جزر فاروس",
    "Diamond Princess": "الأميرة الماسية",
    "Cayman Islands": "جزر كايمان",
    "Tanzania": "تنزانيا",
    "Wallis and Futuna": "واليس وفوتونا",
    "Saint Kitts and Nevis": "سانت كيتس ونيفيس",
    "Brunei": "بروناي",
    "British Virgin Islands": "جزر فيرجن البريطانية",
    "Dominica": "دومينيكا",
    "Grenada": "غرينادا",
    "New Caledonia": "كاليدونيا الجديدة",
    "Anguilla": "أنغيلا",
    "Falkland Islands (Malvinas)": "جزر فوكلاند (مالفيناس)",
    "Macao": "ماكاو",
    "Greenland": "الأرض الخضراء",
    "Holy See (Vatican City State)": "الكرسي الرسولي (دولة الفاتيكان)",
    "Saint Pierre Miquelon": "سان بيير ميكلون",
    "Montserrat": "مونتسيرات",
    "Solomon Islands": "جزر سليمان",
    "Western Sahara": "الصحراء الغربية",
    "MS Zaandam": "MS Zaandam",
    "Marshall Islands": "جزر مارشال",
    "Vanuatu": "فانواتو",
    "Samoa": "ساموا",
    "Saint Helena": "سانت هيلانة",
    "Micronesia": "ميكرونيزيا"
};
